#! /bin/sh
### BEGIN INIT INFO
# Provides:          gpio
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run /etc/rc.local if it exist
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
	# Set out output pin to output on startup
	log_warning_msg "Configuring GPIO"
	# This only needs to be done once and it is remembered across reboots
	# /usr/local/bin/gpio mode 11 down
	/usr/local/bin/gpio mode 11 out
	/usr/local/bin/gpio write 11 0
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
